/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:14eef4db-f74e-4f02-a615-241055b0994f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8EwHhplUB",
    "aws_user_pools_web_client_id": "6fifngea3gfko5e99e009c1nq",
    "authenticationFlowType":'USER_PASSWORD_AUTH',
    "aws_user_files_s3_bucket": "sstyleimg201651-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pleighdlgbfvri5qyh2zgy7o6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
